# @package _group_

common:
  fp16: false
  log_interval: 2
  wandb_project: SL_TD_pose

task:
  _name: SL_topic_detection
  feats_type: ???
  body_parts: LEFT_HAND_LANDMARKS,RIGHT_HAND_LANDMARKS
  feat_dims: "0,1"
  data: ???
  dict_path: ???
  normalization: layer_norm
  min_source_positions: 150
  max_source_positions: 250000
  max_target_positions: 1
  dataset: ''

dataset:
  num_workers: 0
  batch_size: 16
  skip_invalid_size_inputs_valid_test: true
  train_subset: train
  valid_subset: val
  validate_interval_updates: 600

criterion:
  _name: focal_loss
  alpha: "0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1"
  gamma: 2.0  # Default value is 2, controls the focusing factor, higher values focus more on hard examples.

optimization:
  max_update: 3000 #####
  lr: [0.0001]
  update_freq: [1]

optimizer:
  _name: adam
  adam_betas: [0.9, 0.998]
  weight_decay: 0.001

lr_scheduler:
  _name: inverse_sqrt
  warmup_updates: 500

checkpoint:
  keep_last_epochs: 1
  best_checkpoint_metric: acc
  maximize_best_checkpoint_metric: true
  save_dir: ???

model:
  _name: SL_topic_detection_transformer_CLS
  subsample_input: true
  #apply_mask: false
  dropout: 0.2
  #feature_grad_mult: 0.0
  encoder_embed_dim: 128
  encoder_ffn_embed_dim: 512
  #freeze_finetune_updates: 0
  encoder_attention_heads: 8
  encoder_layers: 2

bpe:
  _name: sentencepiece
  sentencepiece_model: ???
